buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2

enabled: true

env:
  MAVEN_OPTS: -Xmx768m
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 2.1.X-hubspot
